name: cosmic-greeter

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4

    - name: De-bloat stock image
      run: |
        rm -r /run/host/usr/share/dotnet
        rm -r /run/host${{ runner.tool_cache }}
    
    - name: Clone cosmic-greeter
      run: |
        git clone https://github.com/pop-os/cosmic-greeter.git
        cd cosmic-greeter

    - name: Install needed packages
      run: |
        DEBIAN_FRONTEND=noninteractive apt update
        DEBIAN_FRONTEND=noninteractive apt install -y \
          dpkg-dev \
          build-essential \
          debhelper-compat
        DEBIAN_FRONTEND=noninteractive apt build-dep . -y
  
    - name: Build debian package
      run: |
        cargo vendor
        tar cf vendor.tar vendor
        dpkg-buildpackage -b -uc -us

    - uses: actions/upload-artifact@v4
      with:
        name: cosmic-greeter
        path: |
            ../*.deb

    - uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main'
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
            ../*.deb