name: cosmic-icons

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/cosmic-icons.yml
  pull_request:
    paths:
      - .github/workflows/cosmic-icons.yml

env:
  PACKAGE: cosmic-icons

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4
    
    - name: Clone Package
      run: |
        DEBIAN_FRONTEND=noninteractive apt install -y git
        git clone "https://github.com/pop-os/${{ env.PACKAGE }}.git"
        cd "${{ env.PACKAGE }}"

    - name: Install needed packages
      run: |
        DEBIAN_FRONTEND=noninteractive apt update
        DEBIAN_FRONTEND=noninteractive apt install -y \
          dpkg-dev \
          build-essential \
          debhelper-compat
        cd "${{ env.PACKAGE }}"
        DEBIAN_FRONTEND=noninteractive apt build-dep -y .
  
    - name: Build debian package
      run: |
        cd "${{ env.PACKAGE }}"
        dpkg-buildpackage -b -uc -us
        mkdir -p $GITHUB_WORKSPACE/build-output
        mv ../*.deb $GITHUB_WORKSPACE/build-output/

    - uses: actions/upload-artifact@v4
      with:
        name: "${{ env.PACKAGE }}"
        path: build-output/*.deb
    
    - name: Delete old assets
      run: |
        DEBIAN_FRONTEND=noninteractive apt install -y jq
        bash scripts/delete_old_assets.sh "${{ env.PACKAGE }}" "${{ secrets.GITHUB_TOKEN }}"

    - uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main'
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
          build-output/*.deb
