name: cosmic-greeter

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4
    
    - name: Clone cosmic-greeter
      run: |
        DEBIAN_FRONTEND=noninteractive apt install -y git
        git clone https://github.com/pop-os/cosmic-greeter.git
        cd cosmic-greeter

    - name: Install needed packages
      run: |
        DEBIAN_FRONTEND=noninteractive apt update
        DEBIAN_FRONTEND=noninteractive apt install -y \
          dpkg-dev \
          build-essential \
          debhelper-compat
        cd cosmic-greeter
        DEBIAN_FRONTEND=noninteractive apt build-dep -y .
  
    - name: Build debian package
      run: |
        cd cosmic-greeter
        cargo vendor
        tar cf vendor.tar vendor
        dpkg-buildpackage -b -uc -us
        mkdir -p $GITHUB_WORKSPACE/build-output
        mv ../*.deb $GITHUB_WORKSPACE/build-output/


    - uses: actions/upload-artifact@v4
      with:
        name: cosmic-greeter
        path: build-output/*.deb

    - uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main'
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
          build-output/*.deb
